# Color Channels

In [2]:
import cv2 as cv
import numpy as np

In [3]:
img = cv.imread('../Resources/Photos/park.jpg')
cv.imshow('Img', img)

cv.waitKey(0)
cv.destroyAllWindows()

### 1. Split

In [7]:
img = cv.imread('../Resources/Photos/park.jpg')
cv.imshow('Img', img)

# split image
# cv dot split bassically split the image into red, green and blue.
r, g, b = cv.split(img)
cv.imshow("red", r)
cv.imshow("green", g)
cv.imshow("blue", b)

# print shape
print("img : ", img)
print("red : ", r)
print("green : ", g)
print("blue : ", b)

cv.waitKey(0)
cv.destroyAllWindows()

img :  [[[210 152 103]
  [210 152 103]
  [210 152 103]
  ...
  [212 142  82]
  [212 142  83]
  [212 142  83]]

 [[210 152 103]
  [210 152 103]
  [210 152 103]
  ...
  [212 142  82]
  [212 142  83]
  [212 142  83]]

 [[210 151 105]
  [210 151 105]
  [210 151 105]
  ...
  [211 141  81]
  [211 141  81]
  [211 141  81]]

 ...

 [[ 23  41  48]
  [ 30  46  53]
  [ 21  34  42]
  ...
  [ 75 101 117]
  [ 67  93 110]
  [ 55  83 100]]

 [[ 25  43  50]
  [ 23  39  46]
  [  5  17  27]
  ...
  [ 62  88 102]
  [ 48  75  89]
  [ 38  65  79]]

 [[ 26  45  50]
  [ 24  40  46]
  [ 12  23  31]
  ...
  [ 49  75  87]
  [ 33  59  71]
  [ 25  51  63]]]
red :  [[210 210 210 ... 212 212 212]
 [210 210 210 ... 212 212 212]
 [210 210 210 ... 211 211 211]
 ...
 [ 23  30  21 ...  75  67  55]
 [ 25  23   5 ...  62  48  38]
 [ 26  24  12 ...  49  33  25]]
green :  [[152 152 152 ... 142 142 142]
 [152 152 152 ... 142 142 142]
 [151 151 151 ... 141 141 141]
 ...
 [ 41  46  34 ... 101  93  83]
 [ 43  39  17 ...  88  75 

### 2. Marged the Three Color image together

In [11]:
merged = cv.merge((r, g, b))
cv.imshow("Merged Image", merged)

cv.waitKey(0)
cv.destroyAllWindows()

### 3. Blue, Green and Red images

In [14]:
# Blank image
blank = np.zeros(img.shape[:2], dtype='uint8')
cv.imshow("Blank", blank)

cv.waitKey(0)
cv.destroyAllWindows()

In [15]:
blue = cv.merge((b, blank, blank))
green = cv.merge((blank, g, blank))
red = cv.merge((blank, blank, r))

cv.imshow("Blue Image", blue)
cv.imshow("Green Image", green)
cv.imshow("Red Image", red)

cv.waitKey(0)
cv.destroyAllWindows()